version: "3.8"

services:
  api-dev:
    build:
      context: .
      target: dev
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    env_file:
      - .env
    environment:
      - NODE_ENV=development

  api-prod:
    build:
      context: .
      target: prod
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
