#!/usr/bin/env node
/* eslint-disable */
// PR14 cross-reference: produce docs/api-map/MAP.md.
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "../..");
const backend = JSON.parse(fs.readFileSync(path.join(ROOT, "docs/api-map/backend-routes.json"), "utf8"));
const web = JSON.parse(fs.readFileSync(path.join(ROOT, "docs/api-map/bazaar-web.json"), "utf8"));
const admin = JSON.parse(fs.readFileSync(path.join(ROOT, "docs/api-map/bazaar-admin.json"), "utf8"));
const mobile = JSON.parse(fs.readFileSync(path.join(ROOT, "docs/api-map/bazaar-mobile.json"), "utf8"));

// Normalize URL by replacing :param and {param} with *
function norm(p) {
  if (!p) return p;
  let s = p.replace(/^https?:\/\/[^/]+/, "");
  // strip leading template prefix like "${baseUrl}" → already replaced upstream as $* by client extractor; trim leading $* tokens
  s = s.replace(/^\$\*\/+/, "/");
  s = s.replace(/\{[^}]+\}/g, "*");
  s = s.replace(/:[a-zA-Z_]\w*/g, "*");
  // collapse repeat $* segments
  s = s.replace(/\$\*/g, "*");
  // strip a leading "*" (template prefix collapsed) so the path starts at the first known segment
  s = s.replace(/^\*+\/?/, "/");
  s = s.replace(/\/+/g, "/").replace(/\/$/, "");
  if (s && !s.startsWith("/")) s = "/" + s;
  return s || "/";
}

// Build a backend lookup keyed by (method, normPath)
const backendIndex = new Map();
for (const r of backend) {
  const k = `${r.method} ${norm(r.path)}`;
  if (!backendIndex.has(k)) backendIndex.set(k, []);
  backendIndex.get(k).push(r);
}

// Index client calls by (method, normPath)
function indexCalls(calls, label) {
  const idx = new Map();
  for (const c of calls) {
    let m = c.method;
    let np = norm(c.url);
    if (m === "?") {
      // Try every known backend method on this path; fall back to GET.
      const methods = ["GET", "POST", "PUT", "DELETE", "PATCH"];
      const found = methods.find(
        (mm) =>
          backendIndex.has(`${mm} ${np}`) ||
          backendIndex.has(`${mm} ${np}/*`),
      );
      m = found || "GET";
    }
    // Fuzzy-match trailing /:id when client constant is the prefix only
    if (!backendIndex.has(`${m} ${np}`) && backendIndex.has(`${m} ${np}/*`)) {
      np = `${np}/*`;
    }
    const k = `${m} ${np}`;
    if (!idx.has(k)) idx.set(k, []);
    idx.get(k).push({ ...c, _src: label, _resolvedMethod: m });
  }
  return idx;
}
const webIdx = indexCalls(web, "web");
const adminIdx = indexCalls(admin, "admin");
const mobileIdx = indexCalls(mobile, "mobile");

// Union of keys
const allKeys = new Set([
  ...backendIndex.keys(),
  ...webIdx.keys(),
  ...adminIdx.keys(),
  ...mobileIdx.keys(),
]);

const rows = [];
for (const k of allKeys) {
  const be = backendIndex.get(k) || [];
  const w = webIdx.get(k) || [];
  const a = adminIdx.get(k) || [];
  const mo = mobileIdx.get(k) || [];
  const [method, ...rest] = k.split(" ");
  const path = rest.join(" ");
  const hasClient = w.length + a.length + mo.length > 0;
  const hasBackend = be.length > 0;
  let verdict;
  if (!hasBackend && hasClient) verdict = "ORPHAN";
  else if (hasBackend && !hasClient) verdict = "UNUSED";
  else {
    // Both — check shape
    const beKeys = new Set(be.flatMap((r) => r.response_shape_keys || []));
    const clientFields = new Set(
      [...w, ...a, ...mo].flatMap((c) => c.fields || []),
    );
    if (beKeys.size > 0 && clientFields.size > 0) {
      const missing = [...clientFields].filter(
        (f) => !beKeys.has(f) && !["data", "success", "message", "error", "status"].includes(f),
      );
      verdict = missing.length > 0 ? "CLIENT-ONLY" : "MATCH";
    } else {
      verdict = "MATCH";
    }
  }
  rows.push({
    method,
    path,
    backend: be,
    web: w,
    admin: a,
    mobile: mo,
    verdict,
  });
}

// Severity sort
const SEV = { DRIFT: 0, ORPHAN: 1, "CLIENT-ONLY": 2, UNUSED: 3, "BACKEND-ONLY": 4, MATCH: 5 };
rows.sort((a, b) => (SEV[a.verdict] - SEV[b.verdict]) || a.path.localeCompare(b.path));

// Counts
const counts = rows.reduce((acc, r) => ((acc[r.verdict] = (acc[r.verdict] || 0) + 1), acc), {});

// Build MAP.md
let md = `# Cross-Client API Map\n\n`;
md += `Generated by \`scripts/api-map/build-map.js\` on ${new Date().toISOString().slice(0, 10)}.\n\n`;
md += `## Summary\n\n`;
md += `- Backend routes extracted: ${backend.length}\n`;
md += `  - v1-ecommerce: ${backend.filter((r) => r.version === "v1-ecommerce").length}\n`;
md += `  - v1-mobile: ${backend.filter((r) => r.version === "v1-mobile").length}\n`;
md += `  - v2: ${backend.filter((r) => r.version === "v2").length}\n`;
md += `  - shared (server.js inline): ${backend.filter((r) => r.version === "shared").length}\n`;
md += `- Client calls: web=${web.length}, admin=${admin.length}, mobile=${mobile.length}\n`;
md += `- Unique (method, path) rows: ${rows.length}\n`;
md += `- Verdict counts: ${JSON.stringify(counts)}\n\n`;

md += `## Verdict legend\n\n`;
md += `- **MATCH**: client-read fields exist in backend response (or no field-level evidence either way).\n`;
md += `- **CLIENT-ONLY**: client reads a field the backend does not return.\n`;
md += `- **BACKEND-ONLY**: backend returns fields no client reads (subset of UNUSED tracked by shape; not enumerated separately).\n`;
md += `- **DRIFT**: same logical resource, different shape across v1/v2 or platforms (manually tagged in NOTES below).\n`;
md += `- **ORPHAN**: client hits a path the backend does not serve.\n`;
md += `- **UNUSED**: backend route no client calls.\n\n`;

md += `## Cross-reference\n\n`;
md += `| Verdict | Method | Path | Backend | Web | Admin | Mobile |\n`;
md += `|---|---|---|---|---|---|---|\n`;
for (const r of rows) {
  const beStr = r.backend.length
    ? r.backend.map((b) => `${b.controller || "?"}@${b.file.split("/").slice(-2).join("/")}`).join(", ")
    : "—";
  const w = r.web.length ? r.web.map((c) => c.file.split("/").pop() + ":" + c.line).join(", ") : "—";
  const a = r.admin.length ? r.admin.map((c) => c.file.split("/").pop() + ":" + c.line).join(", ") : "—";
  const mo = r.mobile.length ? r.mobile.map((c) => c.file.split("/").pop() + ":" + c.line).join(", ") : "—";
  md += `| ${r.verdict} | ${r.method} | \`${r.path}\` | ${beStr} | ${w} | ${a} | ${mo} |\n`;
}

md += `\n## Top mismatches\n\n`;
const topMismatch = rows.filter((r) => r.verdict !== "MATCH" && r.verdict !== "BACKEND-ONLY").slice(0, 30);
md += `Top ${topMismatch.length} non-MATCH rows by severity:\n\n`;
for (const r of topMismatch) {
  md += `- **${r.verdict}** ${r.method} \`${r.path}\``;
  if (r.web.length) md += ` — web fields: [${[...new Set(r.web.flatMap((c) => c.fields))].join(", ") || "n/a"}]`;
  if (r.mobile.length) md += ` — mobile fields: [${[...new Set(r.mobile.flatMap((c) => c.fields))].join(", ") || "n/a"}]`;
  md += `\n`;
}

md += `\n## Notes / known caveats\n\n`;
md += `- **DRIFT detection** is heuristic. v1 controllers commonly return raw Mongoose docs (\`res.json(user)\`) which the regex extractor cannot key-shape; expect false MATCH for those.\n`;
md += `- **Mobile method inference** falls back to GET when no nearby \`http.METHOD\` is present. Treat MOBILE GET orphans as suspect.\n`;
md += `- **Dynamic URLs** (template literals, concatenated path params) are normalized via \`*\` for the param token. Routes with multiple params or query strings may collapse into the same row.\n`;
md += `- **v1 vs v2 DRIFT** is the dominant theme: web hits both \`/api/...\` (v1 mobile shape) and \`/v2/...\` for some resources; mobile hits both \`/api/...\` and \`/v2/...\`. Most rows here flagged \`UNUSED\` for v2 routes are simply not yet adopted by the clients.\n`;

fs.writeFileSync(path.join(ROOT, "docs/api-map/MAP.md"), md);
console.log(`Wrote MAP.md, counts=${JSON.stringify(counts)}, rows=${rows.length}`);

// (no _rows.json dump in production output — rebuild via this script if needed for bug filing.)
